/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bikerentalsystem.gui;

import bikerentalsystem.adt.BikeLinkedList;
import bikerentalsystem.adt.BikeStack;
import bikerentalsystem.adt.UserQueue;
import bikerentalsystem.bike.Bike;
import bikerentalsystem.bike.ElectricBike;
import bikerentalsystem.bike.StandardBike;
import bikerentalsystem.user.User;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.LinkedList;
import java.util.Queue;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 * Main GUI class for the bike rental system.
 * This class manages bike inventory, user requests, and returned bikes.
 * Uses BikeLinkedList, BikeStack, and UserQueue to handle data
 * @author megan
 */
public class BikeRentalAppGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BikeRentalAppGUI.class.getName());
    
    //data members
    private BikeLinkedList allBikes;
    private BikeStack returnedBikes;
    private UserQueue waitingUsers;
    
    /**
     * Creates new form BikeRentalAppGUI
     */
    public BikeRentalAppGUI() {
        initComponents();
        //initialise data members
        allBikes = new BikeLinkedList();
        returnedBikes = new BikeStack();
        waitingUsers = new UserQueue();
        
        //set default visible panel to the Bikes panel
        panelBikes.setVisible(true);
        panelUsers.setVisible(false);
        panelReturns.setVisible(false);
        
        //make text areas read only
        txtAreaBikes.setEditable(false);
        txtAreaQueue.setEditable(false);
        txtAreaReturned.setEditable(false);
        
        //enable/disable battery input depending on bike type selection
        cmbBikeType.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
                if(cmbBikeType.getSelectedItem().equals("Electric")){
                    txtBattery.setEnabled(true);
                } else {
                    txtBattery.setEnabled(false);
                    txtBattery.setText("");
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        panelNav = new javax.swing.JPanel();
        btnBikes = new javax.swing.JButton();
        btnUsers = new javax.swing.JButton();
        btnReturns = new javax.swing.JButton();
        panelBikes = new javax.swing.JPanel();
        lblBikeID = new javax.swing.JLabel();
        lblBikeType = new javax.swing.JLabel();
        txtBikeID = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDisplay = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaBikes = new javax.swing.JTextArea();
        lblBikesTitle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbBikeType = new javax.swing.JComboBox<>();
        txtBattery = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        panelUsers = new javax.swing.JPanel();
        lblUserID = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        btnRequest = new javax.swing.JButton();
        btnViewQueue = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaQueue = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelReturns = new javax.swing.JPanel();
        btnReturn = new javax.swing.JButton();
        btnAssign = new javax.swing.JButton();
        btnDisplayStack = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaReturned = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtReturnBikeID = new javax.swing.JTextField();
        txtReturnBikeModel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(232, 245, 233));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setSize(new java.awt.Dimension(0, 0));

        panelMain.setBackground(new java.awt.Color(232, 245, 233));
        panelMain.setPreferredSize(new java.awt.Dimension(570, 370));

        panelNav.setBackground(new java.awt.Color(27, 94, 32));
        panelNav.setPreferredSize(new java.awt.Dimension(570, 40));

        btnBikes.setBackground(new java.awt.Color(46, 125, 50));
        btnBikes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBikes.setForeground(new java.awt.Color(232, 245, 233));
        btnBikes.setText("Bikes");
        btnBikes.setBorderPainted(false);
        btnBikes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBikesActionPerformed(evt);
            }
        });

        btnUsers.setBackground(new java.awt.Color(46, 125, 50));
        btnUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(232, 245, 233));
        btnUsers.setText("Users");
        btnUsers.setBorderPainted(false);
        btnUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsersActionPerformed(evt);
            }
        });

        btnReturns.setBackground(new java.awt.Color(46, 125, 50));
        btnReturns.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturns.setForeground(new java.awt.Color(232, 245, 233));
        btnReturns.setText("Returned Bikes");
        btnReturns.setBorderPainted(false);
        btnReturns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelNavLayout = new javax.swing.GroupLayout(panelNav);
        panelNav.setLayout(panelNavLayout);
        panelNavLayout.setHorizontalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBikes, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReturns)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        panelNavLayout.setVerticalGroup(
            panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBikes)
                    .addComponent(btnUsers)
                    .addComponent(btnReturns))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        panelBikes.setBackground(new java.awt.Color(232, 245, 233));
        panelBikes.setPreferredSize(new java.awt.Dimension(570, 370));

        lblBikeID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBikeID.setForeground(new java.awt.Color(60, 60, 60));
        lblBikeID.setText("Bike ID:");

        lblBikeType.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBikeType.setForeground(new java.awt.Color(60, 60, 60));
        lblBikeType.setText("Bike Type:");

        txtBikeID.setForeground(new java.awt.Color(85, 85, 85));
        txtBikeID.setText("Enter numeric ID....");

        btnAdd.setBackground(new java.awt.Color(46, 125, 50));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(232, 245, 233));
        btnAdd.setText("Add");
        btnAdd.setBorderPainted(false);
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setBackground(new java.awt.Color(46, 125, 50));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(232, 245, 233));
        btnRemove.setText("Remove");
        btnRemove.setBorderPainted(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(46, 125, 50));
        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(232, 245, 233));
        btnUpdate.setText("Update");
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDisplay.setBackground(new java.awt.Color(46, 125, 50));
        btnDisplay.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDisplay.setForeground(new java.awt.Color(232, 245, 233));
        btnDisplay.setText("Display Bikes");
        btnDisplay.setBorderPainted(false);
        btnDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayActionPerformed(evt);
            }
        });

        txtAreaBikes.setColumns(20);
        txtAreaBikes.setRows(5);
        jScrollPane1.setViewportView(txtAreaBikes);

        lblBikesTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblBikesTitle.setForeground(new java.awt.Color(27, 94, 32));
        lblBikesTitle.setText("Bike Management");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(85, 85, 85));
        jLabel5.setText("Add, update, remove, or view bikes using their ID.");

        cmbBikeType.setForeground(new java.awt.Color(85, 85, 85));
        cmbBikeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Standard", "Electric" }));

        txtBattery.setForeground(new java.awt.Color(85, 85, 85));
        txtBattery.setText("0-100%....");
        txtBattery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBatteryActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(60, 60, 60));
        jLabel8.setText("Battery:");

        javax.swing.GroupLayout panelBikesLayout = new javax.swing.GroupLayout(panelBikes);
        panelBikes.setLayout(panelBikesLayout);
        panelBikesLayout.setHorizontalGroup(
            panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBikesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(panelBikesLayout.createSequentialGroup()
                        .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelBikesLayout.createSequentialGroup()
                                .addComponent(btnDisplay)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(panelBikesLayout.createSequentialGroup()
                                .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBikeType)
                                    .addComponent(lblBikeID))
                                .addGap(18, 18, 18)
                                .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBikeID)
                                    .addGroup(panelBikesLayout.createSequentialGroup()
                                        .addComponent(cmbBikeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBattery, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
            .addGroup(panelBikesLayout.createSequentialGroup()
                .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBikesLayout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(lblBikesTitle))
                    .addGroup(panelBikesLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBikesLayout.setVerticalGroup(
            panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBikesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBikesTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(28, 28, 28)
                .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBikeID)
                    .addComponent(txtBikeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove)
                    .addComponent(btnAdd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelBikesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBikeType)
                    .addComponent(btnUpdate)
                    .addComponent(cmbBikeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBattery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(btnDisplay)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        panelUsers.setBackground(new java.awt.Color(232, 245, 233));
        panelUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panelUsers.setPreferredSize(new java.awt.Dimension(570, 370));

        lblUserID.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserID.setForeground(new java.awt.Color(60, 60, 60));
        lblUserID.setText("User ID:");

        lblUserName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(60, 60, 60));
        lblUserName.setText("Name: ");

        txtUserID.setForeground(new java.awt.Color(85, 85, 85));
        txtUserID.setText("Enter numeric ID....");

        txtUserName.setForeground(new java.awt.Color(85, 85, 85));
        txtUserName.setText("Enter name....");

        btnRequest.setBackground(new java.awt.Color(46, 125, 50));
        btnRequest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRequest.setForeground(new java.awt.Color(232, 245, 233));
        btnRequest.setText("Request Bike");
        btnRequest.setBorderPainted(false);
        btnRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestActionPerformed(evt);
            }
        });

        btnViewQueue.setBackground(new java.awt.Color(46, 125, 50));
        btnViewQueue.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnViewQueue.setForeground(new java.awt.Color(232, 245, 233));
        btnViewQueue.setText("View Queue");
        btnViewQueue.setBorderPainted(false);
        btnViewQueue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewQueueActionPerformed(evt);
            }
        });

        txtAreaQueue.setColumns(20);
        txtAreaQueue.setRows(5);
        jScrollPane2.setViewportView(txtAreaQueue);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 94, 32));
        jLabel1.setText("User Queue Management");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(85, 85, 85));
        jLabel6.setText("Add users to the queue and view waiting users.");

        javax.swing.GroupLayout panelUsersLayout = new javax.swing.GroupLayout(panelUsers);
        panelUsers.setLayout(panelUsersLayout);
        panelUsersLayout.setHorizontalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelUsersLayout.createSequentialGroup()
                        .addComponent(btnRequest)
                        .addGap(18, 18, 18)
                        .addComponent(btnViewQueue))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUsersLayout.createSequentialGroup()
                        .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserID)
                            .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUserID)
                            .addComponent(txtUserName))))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelUsersLayout.setVerticalGroup(
            panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(33, 33, 33)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRequest)
                    .addComponent(btnViewQueue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        panelReturns.setBackground(new java.awt.Color(232, 245, 233));
        panelReturns.setPreferredSize(new java.awt.Dimension(570, 370));

        btnReturn.setBackground(new java.awt.Color(46, 125, 50));
        btnReturn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnReturn.setForeground(new java.awt.Color(232, 245, 233));
        btnReturn.setText("Return Bike");
        btnReturn.setBorderPainted(false);
        btnReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReturnActionPerformed(evt);
            }
        });

        btnAssign.setBackground(new java.awt.Color(46, 125, 50));
        btnAssign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAssign.setForeground(new java.awt.Color(232, 245, 233));
        btnAssign.setText("Assign Bike");
        btnAssign.setBorderPainted(false);
        btnAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignActionPerformed(evt);
            }
        });

        btnDisplayStack.setBackground(new java.awt.Color(46, 125, 50));
        btnDisplayStack.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDisplayStack.setForeground(new java.awt.Color(232, 245, 233));
        btnDisplayStack.setText("Display Returned Bikes");
        btnDisplayStack.setBorderPainted(false);
        btnDisplayStack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayStackActionPerformed(evt);
            }
        });

        txtAreaReturned.setColumns(20);
        txtAreaReturned.setRows(5);
        jScrollPane3.setViewportView(txtAreaReturned);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 94, 32));
        jLabel2.setText("Returned Bikes Management");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 60, 60));
        jLabel3.setText("Return a Bike:");

        txtReturnBikeID.setForeground(new java.awt.Color(85, 85, 85));
        txtReturnBikeID.setText("Enter Bike ID....");
        txtReturnBikeID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReturnBikeIDActionPerformed(evt);
            }
        });

        txtReturnBikeModel.setForeground(new java.awt.Color(85, 85, 85));
        txtReturnBikeModel.setText("Enter Bike Type....");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(60, 60, 60));
        jLabel4.setText("Assign returned bike to waiting user: ");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 85, 85));
        jLabel7.setText("Return bikes and assign them to waiting users.");

        javax.swing.GroupLayout panelReturnsLayout = new javax.swing.GroupLayout(panelReturns);
        panelReturns.setLayout(panelReturnsLayout);
        panelReturnsLayout.setHorizontalGroup(
            panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReturnsLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelReturnsLayout.createSequentialGroup()
                        .addGroup(panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addGroup(panelReturnsLayout.createSequentialGroup()
                                    .addComponent(txtReturnBikeID, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtReturnBikeModel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelReturnsLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btnReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelReturnsLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel7))
                    .addComponent(btnDisplayStack)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        panelReturnsLayout.setVerticalGroup(
            panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReturnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(9, 9, 9)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReturnBikeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReturn)
                    .addComponent(txtReturnBikeModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelReturnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(btnAssign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDisplayStack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelBikes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(panelReturns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBikes, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelReturns, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelMainLayout.createSequentialGroup()
                    .addComponent(panelNav, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 332, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsersActionPerformed
        // TODO add your handling code here:
        panelBikes.setVisible(false);
        panelUsers.setVisible(true);
        panelReturns.setVisible(false);
    }//GEN-LAST:event_btnUsersActionPerformed

    private void btnBikesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBikesActionPerformed
        // TODO add your handling code here:
        panelBikes.setVisible(true);
        panelUsers.setVisible(false);
        panelReturns.setVisible(false);
    }//GEN-LAST:event_btnBikesActionPerformed

    private void btnReturnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnsActionPerformed
        // TODO add your handling code here:
        panelBikes.setVisible(false);
        panelUsers.setVisible(false);
        panelReturns.setVisible(true);
    }//GEN-LAST:event_btnReturnsActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        //read input values and add a bike to the system
        try {
            int id = Integer.parseInt(txtBikeID.getText());
            String type = cmbBikeType.getSelectedItem().toString();
            Bike bike;

            if(type.equals("Electric")) {
                int battery = Integer.parseInt(txtBattery.getText());
                bike = new ElectricBike(battery, id, type, true);
            } else if(type.equals("Standard")) {
                bike = new StandardBike(id, type, true);
            }else{
                bike = new Bike(id, type, true);
            }

            allBikes.add(bike);
            
            //clear input fields after adding
            txtBikeID.setText("");
            txtBattery.setText("");
            cmbBikeType.setSelectedIndex(0);
            
            //confirm to user
            JOptionPane.showMessageDialog(this, "Bike added successfully!");
        }catch(NumberFormatException e) {
            //diplay error if id or batter is not a number
            JOptionPane.showMessageDialog(this, "Bike ID and Battery must be numbers");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestActionPerformed
        // TODO add your handling code here:
        //add a user to the waiting queue
         try {
            int userId = Integer.parseInt(txtUserID.getText());
            String userName = txtUserName.getText();

            if(userName.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter User Name");
                return;
            }

            User user = new User(userId, userName);
            waitingUsers.enqueue(user); //add user to queue

            JOptionPane.showMessageDialog(this, "User added to queue: " + user);

            // Clear input fields
            txtUserID.setText("");
            txtUserName.setText("");

        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "User ID must be a number");
        }
    }//GEN-LAST:event_btnRequestActionPerformed

    private void btnDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayActionPerformed
        // TODO add your handling code here:
        //display all bikes in the system
        if(allBikes.isEmpty()){
            txtAreaBikes.setText("No bikes in the system");
            return;
        }

        StringBuilder sb = new StringBuilder();
        for(int i = 1; i <= allBikes.size(); i++){
            sb.append(allBikes.get(i)).append("\n"); //append each bikes info 
        }
        txtAreaBikes.setText(sb.toString());
    }//GEN-LAST:event_btnDisplayActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
        //remove a bike from the system
        try {
            int bikeId = Integer.parseInt(txtBikeID.getText());
            boolean found = false;

            for(int i = 1; i <= allBikes.size(); i++){
                Bike b = allBikes.get(i);
                if(b.getBikeID() == bikeId){
                    allBikes.remove(i); //remove bike from linked list 
                    found = true;
                    JOptionPane.showMessageDialog(this, "Removed bike: " + b);
                    break;
                }
            }

            if(!found){
                JOptionPane.showMessageDialog(this, "Bike ID not found");
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Bike ID must be a number");
        }
        //clear input fields
        txtBikeID.setText("");
        cmbBikeType.setSelectedIndex(0);
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //update an existing bike's type in the system
        try {
            int bikeId = Integer.parseInt(txtBikeID.getText());
            String newModel = cmbBikeType.getSelectedItem().toString();
            boolean found = false;
            
            //search for bike in linked list
            for(int i = 1; i <= allBikes.size(); i++){
                Bike b = allBikes.get(i);
                if(b.getBikeID() == bikeId){
                    b.setModel(newModel); //update the bike type
                    found = true;
                    JOptionPane.showMessageDialog(this, "Updated bike: " + b);
                    break;
                }
            }

            if(!found){
                JOptionPane.showMessageDialog(this, "Bike ID not found");
            }

        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Bike ID must be a number");
        }
        
        //clear input fields
        txtBikeID.setText("");
        cmbBikeType.setSelectedIndex(0);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnViewQueueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewQueueActionPerformed
        // TODO add your handling code here:
        //display all users currently waiting in the queue
        if(waitingUsers.isEmpty()){
            txtAreaQueue.setText("No users in the queue");
            return;
        }

        StringBuilder sb = new StringBuilder();
        Queue<User> tempQueue = new LinkedList<>();

        //temporarily dequeue to display users
        while(!waitingUsers.isEmpty()){
            User u = (User) waitingUsers.dequeue();
            sb.append(u).append("\n");
            tempQueue.add(u);
        }

        //put users back into the queue
        while(!tempQueue.isEmpty()){
            waitingUsers.enqueue(tempQueue.remove());
        }

        txtAreaQueue.setText(sb.toString());
    }//GEN-LAST:event_btnViewQueueActionPerformed

    private void btnReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReturnActionPerformed
        // TODO add your handling code here:
        //add a returned bike to the returned stack
        try {
            int bikeId = Integer.parseInt(txtReturnBikeID.getText());
            String model = txtReturnBikeModel.getText();

            if(model.isEmpty()){
                JOptionPane.showMessageDialog(this, "Enter Bike Model");
                return;
            }

            Bike bike = new Bike(bikeId, model, true);
            returnedBikes.push(bike); //add bike to stack

            JOptionPane.showMessageDialog(this, "Bike returned successfully: " + bike);

            // Clear input fields
            txtReturnBikeID.setText("");
            txtReturnBikeModel.setText("");

        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Bike ID must be a number");
        }
    }//GEN-LAST:event_btnReturnActionPerformed

    private void txtReturnBikeIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReturnBikeIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtReturnBikeIDActionPerformed

    private void btnDisplayStackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisplayStackActionPerformed
        // TODO add your handling code here:
        //display all returned bikes
        if(returnedBikes.isEmpty()){
            txtAreaReturned.setText("No returned bikes in the system");
            return;
        }

        StringBuilder sb = new StringBuilder();
        Stack<Bike> tempStack = new Stack<>();

        // Pop each bike to display, then push back to maintain order
        while(!returnedBikes.isEmpty()){
            Bike b = (Bike) returnedBikes.pop();
            sb.append(b).append("\n");
            tempStack.push(b);
        }

        // Restore stack
        while(!tempStack.isEmpty()){
            returnedBikes.push(tempStack.pop());
        }

        txtAreaReturned.setText(sb.toString());
    }//GEN-LAST:event_btnDisplayStackActionPerformed

    private void btnAssignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignActionPerformed
        // TODO add your handling code here:
        //assign the top returned bike to the first waiting user
        if(returnedBikes.isEmpty()){
            JOptionPane.showMessageDialog(this, "No returned bikes available");
            return;
        }

        if(waitingUsers.isEmpty()){
            JOptionPane.showMessageDialog(this, "No users waiting in the queue");
            return;
        }

        Bike bike = (Bike) returnedBikes.pop(); //remover bike from stack
        User user = (User) waitingUsers.dequeue(); //remover user from queue

        JOptionPane.showMessageDialog(this, "Assigned bike " + bike + " to user " + user);
    }//GEN-LAST:event_btnAssignActionPerformed

    private void txtBatteryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBatteryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBatteryActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BikeRentalAppGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAssign;
    private javax.swing.JButton btnBikes;
    private javax.swing.JButton btnDisplay;
    private javax.swing.JButton btnDisplayStack;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRequest;
    private javax.swing.JButton btnReturn;
    private javax.swing.JButton btnReturns;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUsers;
    private javax.swing.JButton btnViewQueue;
    private javax.swing.JComboBox<String> cmbBikeType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblBikeID;
    private javax.swing.JLabel lblBikeType;
    private javax.swing.JLabel lblBikesTitle;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel panelBikes;
    private javax.swing.JPanel panelMain;
    private javax.swing.JPanel panelNav;
    private javax.swing.JPanel panelReturns;
    private javax.swing.JPanel panelUsers;
    private javax.swing.JTextArea txtAreaBikes;
    private javax.swing.JTextArea txtAreaQueue;
    private javax.swing.JTextArea txtAreaReturned;
    private javax.swing.JTextField txtBattery;
    private javax.swing.JTextField txtBikeID;
    private javax.swing.JTextField txtReturnBikeID;
    private javax.swing.JTextField txtReturnBikeModel;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
